### ISSUE TITLE
replace the current caching approach with cached markdowns

### ISSUE THREAD

**Issue by idavydov** [bedapub/designit#3]
Currently, we have [some code](https://github.com/bedapub/designit/blob/main/R/vignette_cache.R) to to cache slow parts of vignettes.

This code is ugly and relies on global variables, it also causes some warnings dring R check.

Instead we would like to put slow code into a child markdown document, which can be rendered manually when needed.

After discussing with @banfai we decided to put all the child documents (`Rmd`s and `md`s) into `vignettes/cached`.

**Comment by banfai** [comment]
- [ ] change output from `md` to `html_fragment` (`output: html_fragment`, this generates a self-contained HTML)
- [ ] rename children to `vignettes/cached/_*.Rmd` (`_something.Rmd` are ignored by `pkgdown`, otherwise it renders everthing, even stuff in `.Rbuildignore`)
- [  ] include `vignettes/cached/` in `.Rbuildignore` (so `devtools::build_vignettes()` ignore them)
- include `knit: (\(input, ...) rmarkdown::render(input, output_file = "something.html"))` in the yaml header
- [  ] change `{r, child="cached/something.html"}`

this seems to be working with both devtools and pkgdown

**Comment by idavydov** [comment]
Congrats! 🎉
